### ISSUE TITLE
Question: invariance to evaluation interval

### ISSUE THREAD

**Issue by willtebbutt** [tpgillam/TimeDag.jl#51]
Consider the following example:
```julia
using TimeDag
node = TimeDag.block_node(Block(DateTime(2020, 01, 01):Day(1):DateTime(2020, 01, 05), ones(5)))
v = sum(node)
```
and evaluation over two different time windows:
```julia
julia> evaluate(v, DateTime(2020, 01, 01), DateTime(2020, 01, 06))
Block{Float64}(5 knots)
|                time |   value |
|            DateTime | Float64 |
|---------------------|---------|
| 2020-01-01T00:00:00 |     1.0 |
| 2020-01-02T00:00:00 |     2.0 |
| 2020-01-03T00:00:00 |     3.0 |
| 2020-01-04T00:00:00 |     4.0 |
| 2020-01-05T00:00:00 |     5.0 |


julia> evaluate(v, DateTime(2020, 01, 02), DateTime(2020, 01, 06))
Block{Float64}(4 knots)
|                time |   value |
|            DateTime | Float64 |
|---------------------|---------|
| 2020-01-02T00:00:00 |     1.0 |
| 2020-01-03T00:00:00 |     2.0 |
| 2020-01-04T00:00:00 |     3.0 |
| 2020-01-05T00:00:00 |     4.0 |
```

The docstring for `TimeDag.run_node!` contains the following remark:
```
Consistency: Calling run_node! over a single interval should give the same result as calling it multiple times over a decomposition of that same interval.
```
@tpgillam Could you elaborate on what is meant here? To me, the above looks like an example of this being violated, in the sense that e.g. the value associated with `2020-01-02T00:00:00` is different depending upon which time range we evaluate (which feels like an unavoidable property of cumulative sumation)

**Comment by tpgillam** [comment]
Right, it is poorly worded, apologies!

The key difference here is the mutation of the `state` argument. The "calling it multiple times over a decomposition..." is _implicitly_ referring to the fact that we keep track of the changing state.

i.e. the following two things should be equivalent (in pseudocode)

```julia
t0 = DateTime(2020)
t1 = t0 + Day(1)
t2 = t1 + Day(1)

parent = pulse(Hour(1))  # parent of example node
n = sum(parent)  # example node

# We create a fresh evaluation state, and MANUALLY call `run_node!`
# over the whole interval. Roughly, this is what `evaluate` will (eventually)
# do under the hood.
s1 = TimeDag.create_evaluation_state(n)

# Compute the block of the parent with a call to `evaluate`. This is the input that
# we need.
b_input = evaluate(parent, t0, t2)
b1 = TimeDag.run_node!(n.op, s1, t0, t2, b_input)

# Now evaluate again over [t0, t2), but this time decompose it into [t0, t1) and [t1, t2)
s2 = TimeDag.create_evaluation_state(n)

# First step
b_input = evaluate(parent, t0, t1)
b2_a = TimeDag.run_node!(n.op, s2, t0, t1, b_input)
# Second step — NB we re-use `s2`.
b_input = evaluate(parent, t1, t2)  # WRONG IN GENERAL. Works here because `parent` is stateless.
b2_b = TimeDag.run_node!(n.op, s2, t1, t2, b_input)

b2 = vcat(b2_a, b2_b)

b2 == b1  # (I hope)
```

**Comment by tpgillam** [comment]
This behaviour is relied upon by the batching behaviour — i.e. the result of a call to `evaluate` should not depend on the `batch_interval` supplied.

This is tested for basically all nodes, since we use this helper function:

https://github.com/tpgillam/TimeDag.jl/blob/0947e6e9b780dc584b9dfdb94e3fd6023bf9a4dc/test/common.jl#L23-L48

**Comment by willtebbutt** [comment]
Ahh I see. So this is a distinction between the semantics of `run_node!` and `evaluate`. Might just be worth clarifying this in the docs, or pointing to this issue, or something like that.

**Comment by tpgillam** [comment]
I guess evaluate and run_node! Are at different levels of abstraction.

I think a minimal addition to run node docs would clarify things though. Fancy making a PR?

**Comment by willtebbutt** [comment]
Sounds good. Will do after finishing up #54
